---
name: CI
on:
  push:
    branches:
      - hw1
env:
  BUILD_TYPE: Debug

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Setup cmake
        uses: jwlawson/actions-setup-cmake@v1.13
      - name: Build
        run: |
          cmake -B build
          cmake --build build

  cppcheck:  
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: c-linter
        uses: deep5050/cppcheck-action@main

  clang-format:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: DoozyX/clang-format-lint-action@v0.14
        with:
          source: 'src include tests'
          extensions: 'h,cpp'
          clangFormatVersion: 14
          style: 'file:configs/.clang-format'

  clang-tidy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: cpp-linter/cpp-linter-action@v2

  cpplint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install cpplint
        run: |
          sudo apt-get update -y           
          sudo apt-get install -y cpplint
      - name: Run cpp-lint
        run: cpplint --recursive --filter=-build/include_subdir --filter=-runtime/int --root=./ ./src ./lib/utils/src ./lib/utils/include ./tests        

  test:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Run tests
        run: ctest --output-on-failure --repeat-until-fail 100 --test-dir ./build/tests           