---
name: CI
on:
  push:
    branches:
      - hw1
env:
  build_type: Debug

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Setup cmake
        uses: jwlawson/actions-setup-cmake@v1.13
      - name: Build
        run: |
          cmake -B build -DCMAKE_BUILD_TYPE=${{build_type}} -DCMAKE_EXPORT_COMPILE_COMMANDS=True
          cmake --build build
      - name: Save artifacts
      - uses: actions/upload-artifact@v3
        with:
          path: build/compile_commands.json

  cppcheck:  
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: c-linter
        uses: deep5050/cppcheck-action@main

  clang-format:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: DoozyX/clang-format-lint-action@v0.14
        with:
          source: 'src include tests'
          extensions: 'h,cpp'
          clangFormatVersion: 14
          style: 'file:configs/.clang-format'

  clang-tidy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Install clang-tidy
        run: |
          sudo apt-get update -y           
          sudo apt-get install -y clang-tidy
      - name: Download artifact
        uses: actions/download-artifact@v3
        with:
          path: build/compile_commands.json
      - name: Run clang-tidy
        run: clang-tidy ./src/*.cpp  ./include/*.hpp -p build

  test:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Run tests
        run: ctest --output-on-failure --repeat-until-fail 100 --test-dir ./build/tests           