---
name: CI
on:
  push:
    branches:
      - hw1
env:
  BUILD_TYPE: Debug
jobs:
  cppcheck:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install cppcheck
        run: |
          sudo apt-get update -y           
          sudo apt-get install -y cppcheck
      - name: Run cppcheck
        run: cppcheck --enable=all --suppress=missingInclude --std=c++17 ./src ./tests

  clang-format:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install clang-format
        run: |
          sudo apt-get update -y           
          sudo apt-get install -y clang-format
      - name: Run clang-format
        run: clang-format --dry-run --Werror -style=file:./configs/.clang-format ./src/main.cpp ./lib/utils/src/*.cpp

  clang-tidy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install clang-tidy
        run: |
          sudo apt-get update -y           
          sudo apt-get install -y clang-tidy
      - name: Build
        run: |
          cmake -B build
          cmake --build build
      - name: Run clang-tidy
        run: clang-tidy --config-file=./configs/.clang-tidy ./src/main.cpp ./lib/utils/src/utils.cpp ./lib/utils/include/utils.hpp -p build

  cpplint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install cpplint
        run: |
          sudo apt-get update -y           
          sudo apt-get install -y cpplint
      - name: Run cpp-lint
        run: cpplint --recursive --filter=-build/include_subdir --filter=-runtime/int --root=./ ./src ./lib/utils/src ./lib/utils/include ./tests        

  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Build
        run: |
          cmake -B build
          cmake --build build
      - name: Run tests
        run: ctest --output-on-failure --repeat-until-fail 100 --test-dir ./build/tests           